Algoritmo "par_impar"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/02/2026
Var
// Seção de Declarações das variáveis
      numero: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
      escreva("Digite um numero inteiro:")
      leia(numero)
      se(numero % 2=0) entao
      escreva(" O numero é PAR. ")
      senao
      escreva(" O numero é IMPAR. ")


      fimse


Fimalgoritmo