Algoritmo "nome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/02/2026
Var
// Seção de Declarações das variáveis 
      nome:caracter

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
      escreva(" Digite seu nome completo: ")
      leia(nome)
      escreva(" Ola ", nome, "
      seja bem-vindo(a)!")
Fimalgoritmo