Algoritmo "maior_numero"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/02/2026
Var
// Seção de Declarações das variáveis
      num1: real
      num2: real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
      escreva("Digite o primeiro numero:")
      leia(num1)
      escreva("Digite o segundo numero:")
      leia(num2)
      
      se (num1 > num2) entao
      escreva (" O maior numero é: ", num1)
      senao
      se (num1 > num2) entao
      escreva(" O maior numero é:" ,num2)
      senao
      escreva(" Os dois numeros sao iguais. ")
     
     fimse
     
fimse

Fimalgoritmo