Algoritmo "contagem_crescente"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/02/2026
Var
// Seção de Declarações das variáveis
      contador: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
       para contador de 1 ate 50 faca
          escreva(contador)
          

Fimpara

Fimalgoritmo